server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: reggie_take_out
  profiles:
    active: dev
    group:
      "dev": dev
      "prod": prod
  boot:
    admin:
      client:
        url: http://localhost:9999
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  aop:
    auto: true
    proxy-target-class: true
  data:
    redis:
      host: localhost
      port: 6379

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    map-underscore-to-camel-case: true
  type-aliases-package: com.pf.pojo
  mapper-locations: classpath*:/com/pf/dao/*.xml

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS

management:
  endpoint:
    health:
      show-details: always
      show-components: always
    info:
      enabled: true
    env:
      show-values: always
    configprops:
      show-values: always
    quartz:
      show-values: always
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"

jetcache:
  statIntervalMinutes: 60
  areaInCacheName: true
  remote:
    token: #空间area,创建缓存对象时可以填写
      type: redis
      host: localhost
      port: 6379
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        maxTotal: 50
    dish: #空间area,创建缓存对象时可以填写
      type: redis
      host: localhost
      port: 6379
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        maxTotal: 50

memcached:
  servers: localhost:11211
  poolSize: 10
  opTimeout: 3000